### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by koistya** [kriasoft/node-starter-kit#1]
How do you think, what [schema](https://github.com/kriasoft/graphql-sandbox/blob/master/SCHEMA.md) this GraphQL Sandbox should have? Containing data model for a todo app similar to Wunderlist (user, friends, todo list, todo item etc.), or an event planning app (users, friends, events, attendees, speakers, etc.), blog-publishing app (users, stories, comments etc.), something else? Ideally, it should contain all the GraphQL built-in types: Scalars (Int, Float, String, Boolean, ID), Objects, Interfaces, Unions, Enums, Input Objects, Lists and Non-Null.

**Comment by joshprice** [comment]
Don't think this should be tied to a single schema. A Blog example or a TodoMVC implementation are quite simple and well known, so allow developers to learn/compare on familiar examples.

A more complex example would also be useful to showcase all features of each implementation.

**Comment by sogko** [comment]
Hi guys,

I thought it would be useful to have a checklist of things that we _ideally_ should cover for the schema that we eventually decide to go with.

Let me know what you guys think!

Cheers!

-----

**Schema checklist**

**Schema**
- [ ] Query
- [ ] Mutation
- [ ] Subscription

**Definitions**
- [ ] GraphQLScalarType
- [ ] GraphQLObjectType
- [ ] GraphQLInterfaceType
- [ ] GraphQLUnionType
- [ ] GraphQLEnumType
- [ ] GraphQLInputObjectType
- [ ] GraphQLList
- [ ] GraphQLNonNull

**Scalars**
- [ ] GraphQLInt
- [ ] GraphQLFloat
- [ ] GraphQLString
- [ ] GraphQLBoolean
- [ ] GraphQLID

**Misc** _(Some of these may overlap with the above, but I thought it would be good to be explicit)_
- [ ] Object implementing one or more Interfaces
- [ ] Union of one or more Objects
- [ ] Enum
- [ ] Input Object type
- [ ] Custom scalar
- [ ] Input with one argument
- [ ] Input with default value
- [ ] Input with multiple arguments
- [ ] Input with multiple arguments & multiple default values 
- [ ] Self-referential Object _(e.g. type `User` has a field `friends` that returns a list of `User` type)_

**Type Markers** _(optional? not sure how practical it is)_
- [ ] Nullable type (default)
- [ ] Non-null type: `String!`
- [ ] List type: `[String]`
- [ ] List of non-null types: `[String!]`
- [ ] Non-null list type: `[String]!`
- [ ] Non-null list of non-null types: `[String!]!`


**Reference**
http://graphql.org/docs/api-reference-type-system/
